### PR TITLE
Add a ServerSaveEvent so that player data can be saved every time the server saves

### LINKED ISSUE #24: Lost data on any event other than proper disconnect. Synchronize all every now and then.
As i see in code synchronization happens only on player disconnect. If server crashed or stopped data could be lost.

### PR DESCRIPTION
**Pull request by ExcessiveAmountsOfZombies**
I **haven't** tested how this interacts with your SQL libraries but I've implemented a similar function in my own mod that works. A potential performance benefit could be gained by doing the transaction as a batch, though I'm not sure if your library allows that

This would close #24

### CODE REVIEW

**Comment by MrNavaStar** [comment]
Thanks for this! I look into merging it later today. 

What do you mean doing it by batch? Is that not what begin and end transaction do?

**Comment by MrNavaStar** [comment]
Ah actually it can be improved move the start and end transaction outside the loop. That will make a transaction for all the calls. Just as long as it's for one table

**Comment by ExcessiveAmountsOfZombies** [comment]
ok nice, moved them out of the loop

**Comment by MrNavaStar** [comment]
Sweet. I'll probably make some changes about how this is implemented into the api, but looks good other than that. Thanks!

**Pull request merged**
